version: '3'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    env_file:
      - .env
    expose:
      - '${POSTGRES_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./schema.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    networks:
      - backend_network

  api:
    build:
      context: ./
    image: ai_chatbot_api
    restart: always
    environment:
      POSTGRES_HOST: postgres
    env_file:
      - .env
    expose:
      - '${API_PORT}'
    depends_on:
      - postgres
    networks:
      - backend_network

  nginx:
    image: nginx:1.25.1
    env_file:
      - .env
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/templates:/etc/nginx/templates
    depends_on:
      - api
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
